### ISSUE TITLE
Need number for Amarynceus

### ISSUE THREAD

**Issue by olgalevaniouk** [homermultitext/hmt-authlists#264]

**Comment by StephanieML** [comment]
line reference? where is this showing up? scholia or text?

**Comment by olgalevaniouk** [comment]
It's at 23.630. We were doing the scholia to this line, but the name also appears in the text (and has no number).

While I am at it, we also need numbers for Antodoros of Kyme (scholia, 305v) and Dioskouroi (also scholia, 305v)

And finally, should Molione have a joint number as Molione? They do have separate numbers as Kteatos and Eurytos, but there is no number of "Molione" as a dual.
Thanks,
Olga



Olga Levaniouk
Associate Professor, Classics
University of Washington
Seattle WA 98195

**Comment by StephanieML** [comment]
Amarynceus is urn:cite:hmt:pers.pers941
Antidoros is urn:cite:hmt:pers.pers942

the dioskouroi you can treat like the Ajaxes and double wrap them in the names for Kastor and Pollux. I know we have those two.

Molione we've had come up before and you can again do the double wrapping, since the dual name is a matrinymic, yes?

**Comment by olgalevaniouk** [comment]
Thank you. Yes, Molione is a matronymic. Double-wrapping is what we did for now - though I am not sure I did it ok, perhaps someone can take a look once I get to DC. 
Olga



Olga Levaniouk
Associate Professor, Classics
University of Washington
Seattle WA 98195

**Comment by StephanieML** [comment]
if you tell me the scholion reference I can look at it now.
