### ISSUE TITLE
Ethnic Name Question: Cicones

### ISSUE THREAD

**Issue by mjkell18** [homermultitext/hmt-authlists#312]
I'm not sure whether to identify the Ethnic group "Cicones" with a pers name or a place name. I know they, as a tribe, are geographically associated with Thrace and the City of Ismaros, but "Ismaros," which is mentioned in the Odyssey, does not appear etymologically related to "Cicones." I could not find any particular ancestor from which they may get their name either. 

urn:cts:greekLit:tlg5026:msA.17.73, Κικόνων
urn:cite:hmt:vaimg.VA224VN-0726@0.653,0.6461,0.084,0.024

**Comment by brclar15** [comment]
ah what an excellent question! 

I think linking them to Thrace is too general. Since you've found the city that they come from, I'll link them to that. I cant find an eponymous ancestor either, but I'm not bothered by the fact that they're called Cicones and not Ismarians.

also, your text urn points me to the 73rd main scholion, and your image is from the 73 line of book 17. just so ya know.

Keep up the good work Brian!

**Comment by brclar15** [comment]
added as urn:cite:hmt:place.place443
